# Generated by Django 3.2.13 on 2022-04-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='statu',
            new_name='status',
        ),
    ]
